checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths: [tests/*]

build:
    environment:
        postgresql: false
        mongodb: false
        memcached: true
    nodes:
        analysis:
            project_setup:
                override: ['true']
            tests:
                override: [php-scrutinizer-run]
        tests: true
    tests:
        before:
            - sudo service memcached restart
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
