sudo: false

language: php

php:
  - 7.0
  - 7.1

before_script:
  - phpenv config-add .travis/memcached.ini
  - composer update -a -o

script:
  - vendor/bin/php-cs-fixer fix --dry-run -vv
  - vendor/bin/phpunit
